### ISSUE TITLE
doesn't work with skypack

### ISSUE THREAD

**Issue by mreinstein** [egoist/import-http#33]
my code:

```javascript
import clamp from 'https://cdn.skypack.dev/clamp'

console.log('clamped:', clamp(100, 0, 90))
```

here is what I see when I attempt to build via rollup:

```
> rollup -c rollup.config.js --format es -o bundle.js index.js


index.js → bundle.js...
Downloading https://cdn.skypack.dev/clamp...
Downloading https://unpkg.com//-/clamp@v1.0.1-eZ52O1B6VPLsKDDcdbuR/dist=es2020/clamp.js...
Failed to download https://unpkg.com//-/clamp@v1.0.1-eZ52O1B6VPLsKDDcdbuR/dist=es2020/clamp.js...
[!] (plugin http) Error: Could not load https://unpkg.com//-/clamp@v1.0.1-eZ52O1B6VPLsKDDcdbuR/dist=es2020/clamp.js (imported by https://cdn.skypack.dev/clamp): Not Found
Error: Could not load https://unpkg.com//-/clamp@v1.0.1-eZ52O1B6VPLsKDDcdbuR/dist=es2020/clamp.js (imported by https://cdn.skypack.dev/clamp): Not Found
    at module.exports (C:\Users\Mike\wwwroot\test-u\node_modules\import-http\lib\fetch.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-u@1.0.0 build: `rollup -c rollup.config.js --format es -o bundle.js index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-u@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2020-11-24T18_05_27_724Z-debug.log
```

**Comment by mreinstein** [comment]
@egoist would you be open to a PR that fixes this?

**Comment by cbbfcd** [comment]
problem is in `resolveURL`, i will open to a PR for it.
